### ISSUE TITLE
disable on google maps domains

### ISSUE THREAD

**Issue by xyzzy603** [sellomkantjwa/unpinterested#17]
Google Maps can't find _Pluto, MS_
Google Maps can't find _United States_

*.google.com/maps/*

**Comment by MikeLott-MX** [comment]
Hello @sellomkantjwa,

I'm running into the same issue even after correcting the URL with the addtion of the ../maps suffix.

## RESULT
Google.com/map returns zero results. I am assuming something is getting cached or ❓ 

![image](https://user-images.githubusercontent.com/75039569/107120774-1390ec00-684c-11eb-9548-43c86bf98d9f.png)

## OPTIONS
Would it be possible to if/then the `../maps` element to correct this behavior?

By claiming "..no easy way...", are you plannong on resolving or is it out of scope?

Cheers!

**Comment by sellomkantjwa** [comment]
Hi @MikeLott-MX 
Thanks for weighing in. That screenshot actually unlocks the whole thing for me, in terms of understanding the issue. I thought the issue was that if you search for places on the normal search then you do not get map based results, and fixing that is not trivial. 

Anyway, I think the issue you are having might be fixable and will be working on it. In the meantime, there is a setting to only enable Unpinterested! for image searches. See screenshot below. That is the workaround for now.


![image](https://user-images.githubusercontent.com/5308286/107123437-3223d100-68a6-11eb-92cd-d230ee77a63a.png)

**Comment by sellomkantjwa** [comment]
Reoslved in 0.2.9
